language: en
pipeline:
  - name: SpacyNLP
  - name: WhitespaceTokenizer
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CRFEntityExtractor
  - name: EntitySynonymMapper
  - name: SklearnIntentClassifier
  - name: DucklingEntityExtractor
    timezone: Asia/Mumbai
    locale: en_GB
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: FormPolicy
  - name: KerasPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
